[package]
name = "gpucanvas"
description = "Antialiased 2D vector drawing library"
version = "0.1.0"
license = "MIT"
readme = "README.md"
authors = ["Peter Todorov <ptodorov@cytec.bg>"]
keywords = ["graphics", "canvas", "vector", "drawing", "gpu"]
categories = ["graphics"]
repository = "https://github.com/cytecbg/rscanvas"
edition = "2018"

[dependencies]
fnv = "1.0.6"
bitflags = "1.2.1"
image = "0.23.0-preview.0"
unicode-normalization = "0.1.11"
libc = "0.2.66"
harfbuzz_rs = "1.0.1"

[build-dependencies]
gl_generator = "0.13"
pkg-config = "0.3.11"

[dev-dependencies]
glutin = "0.22.0"
euclid = "0.20.7"
rand = "0.7"
svg = "0.6.0"
usvg = "*"
