[package]
name = "gpucanvas"
description = "Antialiased 2D vector drawing library"
version = "0.1.0"
license = "MIT/Apache-2.0"
readme = "README.md"
authors = ["Peter Todorov <ptodorov@cytec.bg>"]
keywords = ["graphics", "canvas", "vector", "drawing", "gpu"]
categories = ["graphics"]
repository = "https://github.com/cytecbg/rscanvas"
edition = "2018"

[profile.release]
debug = true

[dependencies]
fnv = "1.0.6"
libc = "0.2.66"
bitflags = "1.2.1"
image = "0.23.0-preview.0"
ttf-parser = "0.3"
harfbuzz_rs = "1.0.1"
unicode-bidi = "0.3"
unicode-script = "0.5"
lru_time_cache = "0.9.0"

[build-dependencies]
gl_generator = "0.13"
pkg-config = "0.3.11"

[dev-dependencies]
glutin = "0.22.0"
euclid = "0.20.7"
rand = "0.7"
svg = "0.6.0"
usvg = "0.9.0"
