[package]
name = "gpucanvas"
description = "Antialiased 2D vector drawing library"
version = "0.1.0"
license = "MIT/Apache-2.0"
readme = "README.md"
authors = ["Peter Todorov <ptodorov@cytec.bg>"]
keywords = ["graphics", "canvas", "vector", "drawing", "gpu"]
categories = ["graphics"]
repository = "https://github.com/cytecbg/gpucanvas"
edition = "2018"

[dependencies]
fnv = "1.0.7"
rgb = "0.8.18"
libc = "0.2.71"
imgref = "1.6.1"
bitflags = "1.2.1"
owned_ttf_parser = "0.6.0"
servo-freetype-sys = "4.0.5"
harfbuzz_rs = "1.1.1"
unicode-bidi = "0.3.4"
unicode-script = "0.5.1"
generational-arena = "0.2.8"
#rustybuzz = { git = "https://github.com/RazrFalcon/rustybuzz.git" }
lru = { version = "0.5.1", default-features = false }
image = { version = "0.23.5", optional = true }

[features]
default = ["image-loading"]
image-loading = ["image"]

[build-dependencies]
gl_generator = "0.14.0"

[dev-dependencies]
glutin = "0.24.1"
euclid = "0.20.13"
rand = "0.7"
svg = "0.8.0"
usvg = "0.9.1"
